steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: [ 'package','-Dmaven.test.skip=true' ]


  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/sep6-v2/docker-image-1', '--build-arg=JAR_FILE=target/build-artifact', '.' ]
    images: [ 'gcr.io/sep6-v2/docker-image-1' ]