server:
  port: 6666
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name:
  datasource:
    #    url: jdbc:mysql://10.110.30.4:3307/uni-cache?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql:///main_schema?cloudSqlInstance=sep6-v2:europe-west3:sep6v2sql&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=sep6
    username: root
    password: sep6
    #    username: root
    #    password: Pcp@1024
    driver-class-name: com.mysql.jdbc.Driver


